### PR TITLE
Add new option to fail ratCheck if binaries are found

### LINKED ISSUE #16: Add option for ratCheck to fail if unexpected binaries are found
ratCheck currenty only fails if files are found with missing/invalid licenses and doesn't error if unexpected binaries are found--binaries are simply ignored. However, ASF forbids binaries to be included in releases, so it would be convenient for ``sbt ratCeck`` to fail if unexpected binaries are found in addition to license issues. This does mean that binaries that are expected to be in the source (eg. images, test files) need to be explicitly excluded via the ``ratExcludes`` settings, which might be burdensome for some projects, so ideally this could be an option that could be enabled when needed.

### PR DESCRIPTION
**Pull request by stevedlawrence**
ASF policy is to not allow binaries in releases. This adds a new
'ratCheckBinaries' setting that causes ratCheck to fail if any binaries
are found. This defaults to false to maintain existing behavior,
especially since this option requires that expected binaries (e.g.
images, test files) be excluded via the excludeFilter settting.

Fixes #16

### CODE REVIEW

**Review by jvz — APPROVED** [review]
LGTM. I don't remember if my release infra is working properly anymore, so I'll need to figure that out again. Would you like to add a test for this? The tests are fairly easy to write for sbt plugins.

**Comment by stevedlawrence** [comment]
Yep, I'll add a test.

**Comment by stevedlawrence** [comment]
PR now contains three new tests:
* Binary file exists, ratCheckBinaries := false, so ratCheck passes
* Binary file exists, ratCheckBinaries := true, so ratCheck fails
* Binary file exists, ratCheckBinaries := true, but that binary file is in ratExcludes, so ratCheck passes

Also, minor changes from the previous commit:
* Changed the description of ratCheckBinaries to: ``If true, causes ratCheck to fail if binaries are found``
* Change how we get the numBinaries value out of the map so the ``Integer`` type isn't need

**Comment by stevedlawrence** [comment]
Had a thought, is there a better property name than ``ratCheckBinaries``? That could maybe be confused with ``ratCheck`` and people could think it's a command that checks binaries, rather than a configuration to ``ratCheck``. Perhaps there's a better name, such as ``ratFailBinaries`` or something?

**Comment by jvz** [comment]
That's a good question. I used to have different names for the tasks, but I eventually changed them to match the upstream command names. Maybe there's some inspiration there in Creadur?

**Comment by stevedlawrence** [comment]
Here's the documentation for the maven plugin that some of this plugin I think is based off of: https://creadur.apache.org/rat/apache-rat-plugin/rat-mojo.html

I don't see anything referencing how it handles binaries. And grepping through the maven plugin I also don't see any binary references.

The Ant plugin and CLI seem to have even less options:

https://creadur.apache.org/rat/apache-rat/index.html

https://creadur.apache.org/rat/apache-rat-tasks/index.html

Nothing seems to have this capability that I can find. So I maybe we get to come up with this name?

**Comment by jvz** [comment]
Yes, that's the right project (I tried contributing this upstream once, but they weren't too interested in maintaining it). Go ahead and come up with an appropriate name. It's been a while since I've used sbt daily, so I'm not as well versed in which sbt idiom makes most sense to use here.

**Comment by stevedlawrence** [comment]
Decided to go with ``ratFailBinaries``. Change has been pushed.

**Comment by stevedlawrence** [comment]
Any updates on merging and publishing this?

**Comment by jvz** [comment]
Merging will be simple. I need to figure out how to publish the artifacts again since it's been a while, and the last time I tried to use my CI/CD setup here, it seemed like my Maven Central credentials or something expired. I can probably publish this on a GitHub Maven repo, though I'll need to go bug Sonatype to find out what happened to my MC account.

**Comment by jvz** [comment]
Oh right, I did file an issue about it: #14 is required to get this deploying again. I'll work on that today, and then I'll merge and release this PR. Thanks again!

**Comment by jvz** [comment]
Seems like I just had to regenerate a new Maven Central token (besides the migration in #14). Once this 0.6.1 release tag is publishing properly, then I can add a changelog entry here for the next version before merging to master (merges to master are configured to deploy to Maven Central) and getting a fresh release out.

**Comment by jvz** [comment]
Now that I've got CI and CD working, there appears to be an error with this PR. Can you take a look?

**Comment by jvz** [comment]
Also, feel free to update your info in `build.sbt` in the developers section. I added your name to the previous release, but I don't know what other info you'd like to include (if any).

**Comment by stevedlawrence** [comment]
Looks like it's currently failing because the scala-sbt.org site is down, so Github Actions can't download the plugin dependencies. Hopefully that issue gets resolved soon, i'll keep an eye on it.

I've also added a commit to add my email address to build.sbt. Thanks!

**Comment by stevedlawrence** [comment]
Looks like tests are still failing, but now with an error of
```
Error downloading org.musigma:sbt-rat;sbtVersion=1.0;scalaVersion=2.12:0.7.0-SNAPSHOT
```
Seems like there's some issue where ^scripted can't find the plugin the first time I run it with an empty ~/.ivy2/ directory. If I run ^publishLocal before running ^scripted first all tests pass. I wonder if there's some kind of race condition with ^scripted?

**Comment by stevedlawrence** [comment]
I think I've found the issue. There were some build.propreties files that were forcing a specific sbt version that cause things to fail. Deleting these files seems to fix it.

**Review by jvz — APPROVED** [review]
Alright, let's get this merged and released! I've updated the changelog and snapshot version already to match the expected data (I think I initially made this pipeline with the thought of merging PRs locally before pushing master to get a release, but I've changed habits a bit since then).

**Comment by jvz** [comment]
Looks like this was successfully published as 0.7.0 to Maven Central. Thanks again for the contributions!

**Comment by stevedlawrence** [comment]
Great! Thanks so much!

**Comment by jvz** [comment]
Now that I've got deployments working properly again, it should be much, much easier to make updates to this in the future. There was enough friction in the migration for a blog post I might write later to update my old Travis posts.

**Pull request merged**
